name: LCS
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  flutter_pdfview: ^1.3.2
  intl: ^0.18.1
  image_picker: ^1.0.7
  uuid: ^4.3.3
  open_file: ^3.0.1
  signature: ^5.0.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  flutter_secure_storage: ^9.0.0
  video_player: ^2.2.6
  
  flutter_localizations:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
